<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Estudios', 'doctrine');

/**
 * BaseEstudios
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $nombre_estudio
 * @property Doctrine_Collection $NivelFormacion
 * 
 * @method string              getNombreEstudio()  Returns the current record's "nombre_estudio" value
 * @method Doctrine_Collection getNivelFormacion() Returns the current record's "NivelFormacion" collection
 * @method Estudios            setNombreEstudio()  Sets the current record's "nombre_estudio" value
 * @method Estudios            setNivelFormacion() Sets the current record's "NivelFormacion" collection
 * 
 * @package    facilitadores
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseEstudios extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('estudios');
        $this->hasColumn('nombre_estudio', 'string', 50, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 50,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('NivelFormacion', array(
             'local' => 'id',
             'foreign' => 'id_estudios'));
    }
}