<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('AreasFormacion', 'doctrine');

/**
 * BaseAreasFormacion
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $nombre_area
 * @property Doctrine_Collection $AreasFormacionFacilitador
 * 
 * @method string              getNombreArea()                Returns the current record's "nombre_area" value
 * @method Doctrine_Collection getAreasFormacionFacilitador() Returns the current record's "AreasFormacionFacilitador" collection
 * @method AreasFormacion      setNombreArea()                Sets the current record's "nombre_area" value
 * @method AreasFormacion      setAreasFormacionFacilitador() Sets the current record's "AreasFormacionFacilitador" collection
 * 
 * @package    facilitadores
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseAreasFormacion extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('areas_formacion');
        $this->hasColumn('nombre_area', 'string', 50, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 50,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('AreasFormacionFacilitador', array(
             'local' => 'id',
             'foreign' => 'id_area_formacion'));
    }
}