<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('DisponibilidadTurnos', 'doctrine');

/**
 * BaseDisponibilidadTurnos
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id_disponibilidad_dia
 * @property string $turno
 * @property DisponibilidadDias $DisponibilidadDias
 * 
 * @method integer              getIdDisponibilidadDia()   Returns the current record's "id_disponibilidad_dia" value
 * @method string               getTurno()                 Returns the current record's "turno" value
 * @method DisponibilidadDias   getDisponibilidadDias()    Returns the current record's "DisponibilidadDias" value
 * @method DisponibilidadTurnos setIdDisponibilidadDia()   Sets the current record's "id_disponibilidad_dia" value
 * @method DisponibilidadTurnos setTurno()                 Sets the current record's "turno" value
 * @method DisponibilidadTurnos setDisponibilidadDias()    Sets the current record's "DisponibilidadDias" value
 * 
 * @package    facilitadores
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseDisponibilidadTurnos extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('disponibilidad_turnos');
        $this->hasColumn('id_disponibilidad_dia', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => 4,
             ));
        $this->hasColumn('turno', 'string', 20, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 20,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('DisponibilidadDias', array(
             'local' => 'id_disponibilidad_dia',
             'foreign' => 'id'));
    }
}