<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Parroquia', 'doctrine');

/**
 * BaseParroquia
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $nombre_parroquia
 * @property integer $id_municipio
 * @property Doctrine_Collection $Parroquia
 * @property Doctrine_Collection $Identificacion
 * @property Doctrine_Collection $Ente
 * 
 * @method string              getNombreParroquia()  Returns the current record's "nombre_parroquia" value
 * @method integer             getIdMunicipio()      Returns the current record's "id_municipio" value
 * @method Doctrine_Collection getParroquia()        Returns the current record's "Parroquia" collection
 * @method Doctrine_Collection getIdentificacion()   Returns the current record's "Identificacion" collection
 * @method Doctrine_Collection getEnte()             Returns the current record's "Ente" collection
 * @method Parroquia           setNombreParroquia()  Sets the current record's "nombre_parroquia" value
 * @method Parroquia           setIdMunicipio()      Sets the current record's "id_municipio" value
 * @method Parroquia           setParroquia()        Sets the current record's "Parroquia" collection
 * @method Parroquia           setIdentificacion()   Sets the current record's "Identificacion" collection
 * @method Parroquia           setEnte()             Sets the current record's "Ente" collection
 * 
 * @package    facilitadores
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseParroquia extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('parroquia');
        $this->hasColumn('nombre_parroquia', 'string', 50, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => 50,
             ));
        $this->hasColumn('id_municipio', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Parroquia', array(
             'local' => 'id',
             'foreign' => 'id_municipio'));

        $this->hasMany('Identificacion', array(
             'local' => 'id',
             'foreign' => 'id_parroquia'));

        $this->hasMany('Ente', array(
             'local' => 'id',
             'foreign' => 'id_parroquia'));
    }
}