<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Telefonos', 'doctrine');

/**
 * BaseTelefonos
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id_identificacion
 * @property string $numero
 * @property Identificacion $Identificacion
 * 
 * @method integer        getIdIdentificacion()  Returns the current record's "id_identificacion" value
 * @method string         getNumero()            Returns the current record's "numero" value
 * @method Identificacion getIdentificacion()    Returns the current record's "Identificacion" value
 * @method Telefonos      setIdIdentificacion()  Sets the current record's "id_identificacion" value
 * @method Telefonos      setNumero()            Sets the current record's "numero" value
 * @method Telefonos      setIdentificacion()    Sets the current record's "Identificacion" value
 * 
 * @package    facilitadores
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseTelefonos extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('telefonos');
        $this->hasColumn('id_identificacion', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => 4,
             ));
        $this->hasColumn('numero', 'string', 12, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 12,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Identificacion', array(
             'local' => 'id_identificacion',
             'foreign' => 'id'));
    }
}