<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Parroquia', 'doctrine');

/**
 * BaseParroquia
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $nombre_parroquia
 * @property integer $id_municipio
 * @property Municipio $Municipio
 * @property Doctrine_Collection $Identificacion
 * @property Doctrine_Collection $Ente
 * 
 * @method string              getNombreParroquia()  Returns the current record's "nombre_parroquia" value
 * @method integer             getIdMunicipio()      Returns the current record's "id_municipio" value
 * @method Municipio           getMunicipio()        Returns the current record's "Municipio" value
 * @method Doctrine_Collection getIdentificacion()   Returns the current record's "Identificacion" collection
 * @method Doctrine_Collection getEnte()             Returns the current record's "Ente" collection
 * @method Parroquia           setNombreParroquia()  Sets the current record's "nombre_parroquia" value
 * @method Parroquia           setIdMunicipio()      Sets the current record's "id_municipio" value
 * @method Parroquia           setMunicipio()        Sets the current record's "Municipio" value
 * @method Parroquia           setIdentificacion()   Sets the current record's "Identificacion" collection
 * @method Parroquia           setEnte()             Sets the current record's "Ente" collection
 * 
 * @package    facilitadores
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseParroquia extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('parroquia');
        $this->hasColumn('nombre_parroquia', 'string', 50, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 50,
             ));
        $this->hasColumn('id_municipio', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Municipio', array(
             'local' => 'id_municipio',
             'foreign' => 'id'));

        $this->hasMany('Identificacion', array(
             'local' => 'id',
             'foreign' => 'id_parroquia'));

        $this->hasMany('Ente', array(
             'local' => 'id',
             'foreign' => 'id_parroquia'));
    }
}