<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('BitacoraSecciones', 'doctrine');

/**
 * BaseBitacoraSecciones
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id_secciones
 * @property integer $id_identificacion
 * @property date $fecha
 * @property Secciones $Secciones
 * @property Identificacion $Identificacion
 * 
 * @method integer           getIdSecciones()       Returns the current record's "id_secciones" value
 * @method integer           getIdIdentificacion()  Returns the current record's "id_identificacion" value
 * @method date              getFecha()             Returns the current record's "fecha" value
 * @method Secciones         getSecciones()         Returns the current record's "Secciones" value
 * @method Identificacion    getIdentificacion()    Returns the current record's "Identificacion" value
 * @method BitacoraSecciones setIdSecciones()       Sets the current record's "id_secciones" value
 * @method BitacoraSecciones setIdIdentificacion()  Sets the current record's "id_identificacion" value
 * @method BitacoraSecciones setFecha()             Sets the current record's "fecha" value
 * @method BitacoraSecciones setSecciones()         Sets the current record's "Secciones" value
 * @method BitacoraSecciones setIdentificacion()    Sets the current record's "Identificacion" value
 * 
 * @package    facilitadores
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseBitacoraSecciones extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('bitacora_secciones');
        $this->hasColumn('id_secciones', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => 4,
             ));
        $this->hasColumn('id_identificacion', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => 4,
             ));
        $this->hasColumn('fecha', 'date', 25, array(
             'type' => 'date',
             'notnull' => true,
             'length' => 25,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Secciones', array(
             'local' => 'id_secciones',
             'foreign' => 'id'));

        $this->hasOne('Identificacion', array(
             'local' => 'id_identificacion',
             'foreign' => 'id'));
    }
}