<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Municipio', 'doctrine');

/**
 * BaseMunicipio
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $nombre_municipio
 * @property integer $id_estado
 * @property Estado $Estado
 * @property Doctrine_Collection $Identificacion
 * @property Doctrine_Collection $DisponibilidadTrasladoEstado
 * @property Doctrine_Collection $Ente
 * 
 * @method string              getNombreMunicipio()              Returns the current record's "nombre_municipio" value
 * @method integer             getIdEstado()                     Returns the current record's "id_estado" value
 * @method Estado              getEstado()                       Returns the current record's "Estado" value
 * @method Doctrine_Collection getIdentificacion()               Returns the current record's "Identificacion" collection
 * @method Doctrine_Collection getDisponibilidadTrasladoEstado() Returns the current record's "DisponibilidadTrasladoEstado" collection
 * @method Doctrine_Collection getEnte()                         Returns the current record's "Ente" collection
 * @method Municipio           setNombreMunicipio()              Sets the current record's "nombre_municipio" value
 * @method Municipio           setIdEstado()                     Sets the current record's "id_estado" value
 * @method Municipio           setEstado()                       Sets the current record's "Estado" value
 * @method Municipio           setIdentificacion()               Sets the current record's "Identificacion" collection
 * @method Municipio           setDisponibilidadTrasladoEstado() Sets the current record's "DisponibilidadTrasladoEstado" collection
 * @method Municipio           setEnte()                         Sets the current record's "Ente" collection
 * 
 * @package    facilitadores
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseMunicipio extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('municipio');
        $this->hasColumn('nombre_municipio', 'string', 50, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => 50,
             ));
        $this->hasColumn('id_estado', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Estado', array(
             'local' => 'id_estado',
             'foreign' => 'id'));

        $this->hasMany('Identificacion', array(
             'local' => 'id',
             'foreign' => 'id_municipio'));

        $this->hasMany('DisponibilidadTrasladoEstado', array(
             'local' => 'id',
             'foreign' => 'id_municipio'));

        $this->hasMany('Ente', array(
             'local' => 'id',
             'foreign' => 'id_municipio'));
    }
}