<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Profesion', 'doctrine');

/**
 * BaseProfesion
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id_identificacion
 * @property string $nombre_profesion
 * @property Identificacion $Identificacion
 * 
 * @method integer        getIdIdentificacion()  Returns the current record's "id_identificacion" value
 * @method string         getNombreProfesion()   Returns the current record's "nombre_profesion" value
 * @method Identificacion getIdentificacion()    Returns the current record's "Identificacion" value
 * @method Profesion      setIdIdentificacion()  Sets the current record's "id_identificacion" value
 * @method Profesion      setNombreProfesion()   Sets the current record's "nombre_profesion" value
 * @method Profesion      setIdentificacion()    Sets the current record's "Identificacion" value
 * 
 * @package    facilitadores
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseProfesion extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('profesion');
        $this->hasColumn('id_identificacion', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('nombre_profesion', 'string', 50, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 50,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Identificacion', array(
             'local' => 'id_identificacion',
             'foreign' => 'id'));
    }
}