<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('NivelFormacion', 'doctrine');

/**
 * BaseNivelFormacion
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id_identificacion
 * @property integer $id_estudios
 * @property Estudios $Estudios
 * @property Identificacion $Identificacion
 * 
 * @method integer        getIdIdentificacion()  Returns the current record's "id_identificacion" value
 * @method integer        getIdEstudios()        Returns the current record's "id_estudios" value
 * @method Estudios       getEstudios()          Returns the current record's "Estudios" value
 * @method Identificacion getIdentificacion()    Returns the current record's "Identificacion" value
 * @method NivelFormacion setIdIdentificacion()  Sets the current record's "id_identificacion" value
 * @method NivelFormacion setIdEstudios()        Sets the current record's "id_estudios" value
 * @method NivelFormacion setEstudios()          Sets the current record's "Estudios" value
 * @method NivelFormacion setIdentificacion()    Sets the current record's "Identificacion" value
 * 
 * @package    facilitadores
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseNivelFormacion extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('nivel_formacion');
        $this->hasColumn('id_identificacion', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => 4,
             ));
        $this->hasColumn('id_estudios', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Estudios', array(
             'local' => 'id_estudios',
             'foreign' => 'id'));

        $this->hasOne('Identificacion', array(
             'local' => 'id_identificacion',
             'foreign' => 'id'));
    }
}