<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('AreasFormacionFacilitador', 'doctrine');

/**
 * BaseAreasFormacionFacilitador
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id_identificacion
 * @property integer $id_area_formacion
 * @property integer $estatus
 * @property AreasFormacion $AreasFormacion
 * @property Identificacion $Identificacion
 * @property Doctrine_Collection $BitacoraFormacionFacilitador
 * 
 * @method integer                   getIdIdentificacion()             Returns the current record's "id_identificacion" value
 * @method integer                   getIdAreaFormacion()              Returns the current record's "id_area_formacion" value
 * @method integer                   getEstatus()                      Returns the current record's "estatus" value
 * @method AreasFormacion            getAreasFormacion()               Returns the current record's "AreasFormacion" value
 * @method Identificacion            getIdentificacion()               Returns the current record's "Identificacion" value
 * @method Doctrine_Collection       getBitacoraFormacionFacilitador() Returns the current record's "BitacoraFormacionFacilitador" collection
 * @method AreasFormacionFacilitador setIdIdentificacion()             Sets the current record's "id_identificacion" value
 * @method AreasFormacionFacilitador setIdAreaFormacion()              Sets the current record's "id_area_formacion" value
 * @method AreasFormacionFacilitador setEstatus()                      Sets the current record's "estatus" value
 * @method AreasFormacionFacilitador setAreasFormacion()               Sets the current record's "AreasFormacion" value
 * @method AreasFormacionFacilitador setIdentificacion()               Sets the current record's "Identificacion" value
 * @method AreasFormacionFacilitador setBitacoraFormacionFacilitador() Sets the current record's "BitacoraFormacionFacilitador" collection
 * 
 * @package    facilitadores
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseAreasFormacionFacilitador extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('areas_formacion_facilitador');
        $this->hasColumn('id_identificacion', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => 4,
             ));
        $this->hasColumn('id_area_formacion', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => 4,
             ));
        $this->hasColumn('estatus', 'integer', 1, array(
             'type' => 'integer',
             'notnull' => true,
             'default' => 0,
             'length' => 1,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('AreasFormacion', array(
             'local' => 'id_area_formacion',
             'foreign' => 'id'));

        $this->hasOne('Identificacion', array(
             'local' => 'id_identificacion',
             'foreign' => 'id'));

        $this->hasMany('BitacoraFormacionFacilitador', array(
             'local' => 'id',
             'foreign' => 'id_area_formacion_facilitador'));
    }
}