<?php

/**
 * AreasFormacionFacilitadorTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AreasFormacionFacilitadorTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object AreasFormacionFacilitadorTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('AreasFormacionFacilitador');
    }
    
    public static function obtenerAreasFormacionPorFacilitador($idFacilitador)
    {
        $q = Doctrine_Query::create()
                ->from('AreasFormacionFacilitador aff')
                ->where('aff.id_identificacion = ?', $idFacilitador);
                
        return $q->execute();
    }
}
