<?php

/**
 * DisponibilidadTurnosTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class DisponibilidadTurnosTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object DisponibilidadTurnosTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('DisponibilidadTurnos');
    }
}