<?php

/**
 * DisponibilidadDias
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    facilitadores
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class DisponibilidadDias extends BaseDisponibilidadDias
{
  public static function obtenerDiasPorFacilitador($idFacilitador)
    {
      $querystring = Doctrine_Core::getTable('DisponibilidadDias')->createQuery()->where('id_identificacion=?',$idFacilitador);

        return $querystring->execute();
  }
    
    public static function eliminarDiasPorFacilitador($idcorreo)
    {
	   
  
    }
}
