<!--
Document / Documento: DisponibilidadDiasTable.class

Created on / Creado : 23/05/2012, 10:39:10 AM

Author / Desarrolladores:
1. Raúl Lobo 04267711578 andrescerrada@gmail.com
2. José Ruiz 04265752819 jruiz@cenditel.gob.ve joseph2283@gmail.com
3. Jesús Becerra 04263779960 jbecerra@cenditel.gob.ve jesusignaciob@gmail.com
4. Rodolfo Sumoza 04166342086 rsumoza@cenditel.gob.ve rsumoza@gmail.com

Description / Comentarios:
Este archivo genera las siguientes funciones:
1- Obtiene Disponibilidad Dias.
2- Obtiene Disponibilidad Dias por Facilitador.
3- Eliminar Disponibilidad Dias.
-->
<?php

/**
 * DisponibilidadDiasTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class DisponibilidadDiasTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object DisponibilidadDiasTable
     */
//Función que Obtiene Disponibilidad Dias.
    public static function getInstance()
    {
        return Doctrine_Core::getTable('DisponibilidadDias');
    }
//Función que Obtiene Disponibilidad Dias por Facilitador.
      public static function obtenerDiasTurnoFacilitador($idFacilitador)
    {
      $querystring = Doctrine_Core::getTable('DisponibilidadDias')->createQuery()->where('id_identificacion=?',$idFacilitador);

        return $querystring->execute();
    }
//Función Eliminar Disponibilidad Dias.    
    public static function eliminarDias($id)
    {
	   $deleted = Doctrine_Query::create()
	  ->delete()
	  ->from('DisponibilidadDias')
	  ->andWhere('id_identificacion = ?', $id)
	  ->execute(); 
  
    }
}
