<?php

/**
 * DisponibilidadDiasTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class DisponibilidadDiasTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object DisponibilidadDiasTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('DisponibilidadDias');
    }
}