<!--
Document / Documento: EstudiosTable.class

Created on / Creado : 23/05/2012, 10:39:10 AM

Author / Desarrolladores:
1. Raúl Lobo 04267711578 andrescerrada@gmail.com
2. José Ruiz 04265752819 jruiz@cenditel.gob.ve joseph2283@gmail.com
3. Jesús Becerra 04263779960 jbecerra@cenditel.gob.ve jesusignaciob@gmail.com
4. Rodolfo Sumoza 04166342086 rsumoza@cenditel.gob.ve rsumoza@gmail.com

Description / Comentarios:
Este archivo genera las siguientes funciones:
1- Obtiene Estudios.
2- Obtiene y ordena estudios por el nombre.
-->
<?php

/**
 * EstudiosTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class EstudiosTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object EstudiosTable
     */
//Función que Obtiene Estudios.
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Estudios');
    }
//Función que Obtiene y ordena estudios por el nombre.
    public function getEstudios() {
      $query = $this->getInstance()->createQuery()
                    ->orderBy('nombre_estudio');
      return $query->execute();
    }
}
