<?php

/**
 * Estudios
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    facilitadores
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Estudios extends BaseEstudios
{
//Funcion para obtener los nombres de estudio de la tabla estudios
	public function __toString() 
	{
    		return $this->getnombre_estudio();
  	}
}
