<?php

/**
 * NivelFormacionTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class NivelFormacionTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object NivelFormacionTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('NivelFormacion');
    }
    public static function obtenerNivelFormacionPorFacilitador($idFacilitador)
    {
        $q = Doctrine_Query::create()
                ->from('NivelFormacion nff')
                ->where('nff.id_identificacion = ?', $idFacilitador);
                
        return $q->execute();
    }
}
