<?php

/**
 * ProfesionTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ProfesionTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ProfesionTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Profesion');
    }
}