# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/13-View

default:
  http_metas:
    content-type: text/html

  metas:
    title:        Sistema Gestión Facilitadores GMSTV - CENDITEL
    #description:  symfony project
    #keywords:     symfony, project
    #language:     en
    #robots:       index, follow

  stylesheets:    [main.css, sms-theme/jquery-ui-1.8.17.custom.css]

  javascripts:    [jquery-1.7.1.min.js, jquery-ui-1.8.17.custom.min.js]

  has_layout:     true
  layout:         layout
