# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/13-View

default:
  has_layout:     true
  layout:         layout
  javascripts:    [jquery-1.7.1.min.js, jquery-ui-1.8.17.custom.min.js, filtro_geo.js, filtro_geo_traslados.js, filtro_geo_ente.js, filtro_geo_secciones.js, facilitadoresList.js, jquery.ui.core.js, jquery.ui.position.js, jquery.ui.widget.js, jquery.ui.dialog.js]
