<?php

/**
 * AreasFormacionTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AreasFormacionTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object AreasFormacionTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('AreasFormacion');
    }
    
    public static function obtenerTodos()
    {
      return Doctrine_Core::getTable('AreasFormacion')->createQuery()->execute();
    }
}
