<?php

/**
 * BitacoraFormacionFacilitadorTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class BitacoraFormacionFacilitadorTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object BitacoraFormacionFacilitadorTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('BitacoraFormacionFacilitador');
    }
}