<?php

/**
 * CorreosTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CorreosTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object CorreosTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Correos');
    }
    
    public static function obtenerCorreosPorFacilitador($idFacilitador)
    {
      $querystring = Doctrine_Core::getTable('Correos')->createQuery()->where('id_identificacion=?',$idFacilitador);

        return $querystring->execute();
    }
}
