<?php

/**
 * DisponibilidadDiasTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class DisponibilidadDiasTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object DisponibilidadDiasTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('DisponibilidadDias');
    }

      public static function obtenerDiasTurnoFacilitador($idFacilitador)
    {
      $querystring = Doctrine_Core::getTable('DisponibilidadDias')->createQuery()->where('id_identificacion=?',$idFacilitador);

        return $querystring->execute();
    }
    
    public static function eliminarDias($id)
    {
	   $deleted = Doctrine_Query::create()
	  ->delete()
	  ->from('DisponibilidadDias')
	  ->andWhere('id_identificacion = ?', $id)
	  ->execute(); 
  
    }
}
