<?php

/**
 * EnteTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class EnteTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object EnteTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Ente');
    }

    public function getEntes() {
      $query = $this->getInstance()->createQuery()
                    ->orderBy('nombre_ente');
      return $query->execute();
    }
}