<!--
Document / Documento: EstadoTable.class

Created on / Creado : 23/05/2012, 10:39:10 AM

Author / Desarrolladores:
1. Raúl Lobo 04267711578 andrescerrada@gmail.com
2. José Ruiz 04265752819 jruiz@cenditel.gob.ve joseph2283@gmail.com
3. Jesús Becerra 04263779960 jbecerra@cenditel.gob.ve jesusignaciob@gmail.com
4. Rodolfo Sumoza 04166342086 rsumoza@cenditel.gob.ve rsumoza@gmail.com

Description / Comentarios:
Este archivo genera las siguientes funciones:
1- Obtiene Estados.
2- Obtiene y ordena estados por el nombre.
-->
<?php

/**
 * EstadoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class EstadoTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object EstadoTable
     */
//Función que Obtiene Estados.
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Estado');
    }
//Función que Obtiene y ordena estados por el nombre.
    public function getEstados() {
      $query = $this->getInstance()->createQuery()
                    ->orderBy('nombre_estado');
      return $query->execute();
    }
}
