<?php

/**
 * EstudiosTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class EstudiosTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object EstudiosTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Estudios');
    }

    public function getEstudios() {
      $query = $this->getInstance()->createQuery()
                    ->orderBy('nombre_estudio');
      return $query->execute();
    }
}