<?php

/**
 * MunicipioTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class MunicipioTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object MunicipioTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Municipio');
    }

    public static function obtenerMunicipiosPorEstado($idEstado)
    {
        $querystring = Doctrine_Core::getTable('Municipio')->createQuery()->where('id_estado=?',$idEstado)->orderBy('nombre_municipio');

        return $querystring->execute();
    }
}
