<!--
Document / Documento: NivelFormacionTable.class

Created on / Creado : 23/05/2012, 10:39:10 AM

Author / Desarrolladores:
1. Raúl Lobo 04267711578 andrescerrada@gmail.com
2. José Ruiz 04265752819 jruiz@cenditel.gob.ve joseph2283@gmail.com
3. Jesús Becerra 04263779960 jbecerra@cenditel.gob.ve jesusignaciob@gmail.com
4. Rodolfo Sumoza 04166342086 rsumoza@cenditel.gob.ve rsumoza@gmail.com

Description / Comentarios:
Este archivo genera las siguientes funciones:
1- Obtiene Nivel Formacion.
2- Obtiene Nivel Formacion Por Facilitador.
3- Elimina Nivel Formacion.
-->
<?php

/**
 * NivelFormacionTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class NivelFormacionTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object NivelFormacionTable
     */
//Función que Obtiene Nivel Formacion.
    public static function getInstance()
    {
        return Doctrine_Core::getTable('NivelFormacion');
    }
//Función que Obtiene Nivel Formacion Por Facilitador
    public static function obtenerNivelFormacionPorFacilitador($idFacilitador)
    {
        $q = Doctrine_Query::create()
                ->from('NivelFormacion nff')
                ->where('nff.id_identificacion = ?', $idFacilitador);
                
        return $q->execute();
    }
//Función que elimina Nivel Formacion
     public static function eliminarNivelFormacion($id_nivel)
	{
 	 $deleted = Doctrine_Query::create()
  	->delete()
  	->from('NivelFormacion')
  	->andWhere('id = ?', $id_nivel)
  	->execute();
	}
}
