<?php

/**
 * SeccionesTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class SeccionesTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object SeccionesTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Secciones');
    }

    public function getSecciones() {
      $query = $this->getInstance()->createQuery()
                    ->orderBy('nombre_seccion');
      return $query->execute();
    }
}