<?php

/**
 * TelefonosTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TelefonosTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TelefonosTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Telefonos');
    }
    
    public static function obtenerTelefonosPorFacilitador($idFacilitador)
    {
      $querystring = Doctrine_Core::getTable('Telefonos')->createQuery()->where('id_identificacion=?',$idFacilitador);

        return $querystring->execute();
    }

public static function eliminarTelefono($id_telefono)
    {
  $deleted = Doctrine_Query::create()
  ->delete()
  ->from('Telefonos')
  ->andWhere('id = ?', $id_telefono)
  ->execute();
    }

}
