<?php

/**
 * TelefonosTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TelefonosTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TelefonosTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Telefonos');
    }
}